### ISSUE TITLE
Падает сборка yate в Windows

### ISSUE THREAD

**Issue by dpolyakov** [andychups/bem-simple-project-stub#2]
``` log
Error: The technology "yate" throw compile error. Error: ENOENT, no such file or directory 'D:\projects\bem-simple-project-stub\desktop.bundles\common\projectsbem-simple-project-stubdesktop.blocksbuttonbutton.yate'
    at methods.compile (D:\projects\bem-simple-project-stub\.enb\techs\yate.js:77:15)
    at builder (D:\projects\bem-simple-project-stub\.enb\techs\yate.js:31:17)
    at resultTechMethods._getBuildResult (D:\projects\bem-simple-project-stub\node_modules\enb\lib\build-flow.js:599:34)
    at D:\projects\bem-simple-project-stub\node_modules\enb\lib\build-flow.js:657:67
    at Array.<anonymous> (D:\projects\bem-simple-project-stub\node_modules\enb\node_modules\vow\lib\vow.js:202:56)
    at Immediate.callFns [as _onImmediate] (D:\projects\bem-simple-project-stub\node_modules\enb\node_modules\vow\lib\vow.js:462:35)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
```

**Comment by andychups** [comment]
```
projectsbem-simple-project-stubdesktop.blocksbuttonbutton.yate
```

– похоже из-за этого. Пусть повисит пока.
